# Generated by Django 3.1.2 on 2020-10-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allow_comment',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1),
        ),
    ]
