# Generated by Django 3.1.2 on 2020-10-10 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edureka_cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Course End Date'),
            preserve_default=False,
        ),
    ]
